// Auto-generated by build.rs - DO NOT EDIT

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ModelId {
    SvgMicro,
}

impl ModelId {
    pub fn name(&self) -> &'static str {
        match self {
            ModelId::SvgMicro => "svg-micro",
        }
    }

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "svg-micro" => Some(ModelId::SvgMicro),
            _ => None,
        }
    }
}

impl Default for ModelId {
    fn default() -> Self {
        // Return the first model (alphabetically)
        AVAILABLE_MODELS[0]
    }
}

pub const AVAILABLE_MODELS: &[ModelId] = &[
    ModelId::SvgMicro,
];

// Generated FFI bridge modules
pub mod ffi {
    pub mod svg_micro;
}
